import PageLayout from '@/components/PageLayout';
import { SITE_CONFIG } from '@/config/site';

export default function TermsPage() {
  return (
    <PageLayout title="Terms of Service" subtitle={`Last updated: January ${SITE_CONFIG.copyrightYear}`}>
      <p>
        By downloading or using My Calories, you agree to these terms. Please read them carefully.
      </p>

      <Section title="Use of the app">
        <p>
          My Calories is provided as a nutrition tracking tool. You agree to use the app for
          personal, lawful purposes and not to misuse or attempt to disrupt the service.
        </p>
      </Section>

      <Section title="AI features">
        <p>
          Food recognition, nutrition estimates, and AI coaching are generated by artificial
          intelligence and may contain errors. AI outputs are informational only and do not
          constitute medical, dietary, or professional advice. Always consult a qualified
          professional for health-related decisions.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You are responsible for maintaining the security of your account and for all activity
          that occurs under your account.
        </p>
      </Section>

      <Section title="Data and content">
        <p>
          You retain ownership of the data you create, including meals, photos, and progress
          entries. You are responsible for the accuracy of the information you input.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          My Calories is provided "as is" without warranties of any kind. We are not liable for any
          damages arising from the use of the app or reliance on its AI-generated content.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          We may update these terms from time to time. Continued use of the app after changes
          constitutes acceptance of the updated terms.
        </p>
      </Section>

      <Section title="Contact">
        <p>For questions about these terms, contact us at {SITE_CONFIG.supportEmail}.</p>
      </Section>
    </PageLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-ink-100 bg-white p-6">
      <h2 className="font-display text-xl font-700 text-ink-900">{title}</h2>
      <div className="mt-3 space-y-2 text-ink-600">{children}</div>
    </div>
  );
}
